# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "93e7dddd6e932630943e5870bed5107e"
name = "ai-commerce-agent"
application_url = "https://agent-web-pi8k.onrender.com"

embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_products,read_customers"

[auth]
redirect_urls = [
  "https://agent-api-84tq.onrender.com/api/oauth/shopify/callback"
]
